name       : ack
version    : '2.23_02'
release    : 9
source     :
    - https://github.com/beyondgrep/ack2/archive/2.23_02.tar.gz : 9fe51f7bc6d3a9d474c5dd4b878501d734e6fcd96436c1c709853f65ae1027fa
license    : Artistic-2.0
component  : system.utils
summary    : ack - grep-like text finder
description: |
    ack - grep-like text finder
rundeps    :
    - perl-file-next
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
