name       : ack
version    : 2.17.01
release    : 5
source     :
    - https://github.com/petdance/ack2/archive/2.17_01.tar.gz : 81fd28e0d96981e5d906c4231da19ada7445e701c4454cfdecd7274b9364d575
license    : Artistic-Perl-2.0
component  : system.utils
summary    : ack - grep-like text finder
description: |
    ack - grep-like text finder
rundeps    :
    - perl-file-next
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
