name       : ack
version    : '2.28'
release    : 17
source     :
    - https://github.com/beyondgrep/ack2/archive/2.28.tar.gz : fa4ca29a31cb219f9fbe1c8f95e13e55e42b6a317f6c9110bddc0d9e46f1b9ba
license    : Artistic-2.0
component  : system.utils
summary    : ack - grep-like text finder
description: |
    ack - grep-like text finder
rundeps    :
    - perl-file-next
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
