name       : ack
version    : 2.15_02
release    : 1
source     :
    - http://search.cpan.org/CPAN/authors/id/P/PE/PETDANCE/ack-2.15_02.tar.gz : 893e46a9263b446d9bd7efeae52c12fbee6092a3a5b9f816d8f84c1644ad7199
license    : Artistic-Perl-2.0
component  : system.utils
summary    : ack - grep-like text finder
description: |
    ack - grep-like text finder
rundeps    :
    - perl-file-next
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
