name       : ack
version    : '2.24'
release    : 12
source     :
    - https://github.com/beyondgrep/ack2/archive/2.24.tar.gz : fe7404f889aff44fcd81808ea2aa32f9302577f9f313cb7c8933dded1ae3f5d3
license    : Artistic-2.0
component  : system.utils
summary    : ack - grep-like text finder
description: |
    ack - grep-like text finder
rundeps    :
    - perl-file-next
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
