name       : ack
version    : 3.7.0
release    : 19
source     :
    - https://github.com/beyondgrep/ack3/archive/refs/tags/v3.7.0.tar.gz : 91b28ef612de4f3c02b93283f21fabe0841a0b936b3d782bc28b9acdc05e18e5
homepage   : https://beyondgrep.com/
license    : Artistic-2.0
component  : system.utils
summary    : ack is a grep-like search tool optimized for source code
description: |
    ack is a code-searching tool, similar to grep but optimized for programmers searching large trees of source code. It is highly portable and runs on any platform that runs Perl.
rundeps    :
    - perl-file-next
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
