name       : ack
version    : '2.16'
release    : 4
source     :
    - https://github.com/petdance/ack2/archive/2.16.tar.gz : 4457ce6b500550501934fbf9c3dcfc911b69c77a9bdd488ae8572e8bf358ed22
license    : Artistic-Perl-2.0
component  : system.utils
summary    : ack - grep-like text finder
description: |
    ack - grep-like text finder
rundeps    :
    - perl-file-next
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
